import type { Metadata } from "next";
import { cache } from "react";
import {
  getDocs,
  getDuplicateTitles,
  getShortSection,
  type Doc,
} from "@/lib/docs";
import { absoluteUrl, SITE_NAME } from "@/lib/site";

/**
 * Shared robots directives. Placeholder pages stay `follow` so link equity
 * still flows through them, but are kept out of the index until authored.
 */
export const INDEX_ROBOTS: Metadata["robots"] = {
  index: true,
  follow: true,
  googleBot: {
    index: true,
    follow: true,
    "max-image-preview": "large",
    "max-snippet": -1,
    "max-video-preview": -1,
  },
};

export const NOINDEX_ROBOTS: Metadata["robots"] = {
  index: false,
  follow: true,
};

/** Site-wide OG image generated by src/app/opengraph-image.tsx. */
export const OG_IMAGE = absoluteUrl("/opengraph-image");
export const OG_IMAGE_SIZE = { width: 1200, height: 630 } as const;

/**
 * Hand-written titles for pages with real, authored content. Keyed by
 * `section-slug/topic-slug`. Each one stays within what the page actually
 * covers — no "complete guide" filler.
 */
const TITLE_OVERRIDES: Record<string, string> = {
  // Fundamentals
  "go-fundamentals/installation-and-setup": "Install Go: Setup and Installation Guide",
  "go-fundamentals/variables": "Go Variables: Declaration, Scope and Zero Values",
  "go-fundamentals/constants": "Go Constants: Typed Constants, Naming and Usage",
  "go-fundamentals/data-types": "Go Data Types: Primitives, Strings and Composite Types",
  "go-fundamentals/type-conversion": "Go Type Conversion: Converting Between Types",
  "go-fundamentals/operators": "Go Operators: Arithmetic, Comparison and Logical",
  "go-fundamentals/input-and-output": "Go Input and Output with fmt",
  "go-fundamentals/if-else": "Go if/else: Conditional Statements with Examples",
  "go-fundamentals/switch": "Go switch: Expression, Type Switch and fallthrough",
  "go-fundamentals/for-loops": "Go for Loops: range, break, continue and Examples",

  // Core Programming
  "go-core-programming/functions": "Go Functions: Parameters, Return Values and Examples",
  "go-core-programming/multiple-return-values": "Go Multiple Return Values: Syntax and Examples",
  "go-core-programming/variadic-functions": "Go Variadic Functions: Syntax and Examples",
  "go-core-programming/anonymous-functions-and-closures":
    "Go Anonymous Functions and Closures",
  "go-core-programming/arrays": "Go Arrays: Fixed-Length Collections",
  "go-core-programming/slices": "Go Slices: Working with Dynamic Arrays",
  "go-core-programming/strings": "Go Strings: Operations and the strings Package",
  "go-core-programming/runes-and-bytes": "Go Runes and Bytes: UTF-8 and Byte Slices",
  "go-core-programming/maps": "Go Maps: Creating, Reading and Iterating",
  "go-core-programming/structs": "Go Structs: Defining and Using Custom Types",
  "go-core-programming/pointers": "Go Pointers: Addresses, Dereferencing and Use Cases",
  "go-core-programming/methods": "Go Methods: Value and Pointer Receivers",
  "go-core-programming/packages": "Go Packages: Organizing and Importing Code",
  "go-core-programming/go-modules": "Go Modules: Dependencies and Project Setup",

  // Advanced Language Features
  "go-advanced-language-features/interfaces":
    "Go Interfaces: Implicit Implementation and Composition",
  "go-advanced-language-features/empty-interface":
    "Go Empty Interface (any): Usage, Trade-offs and JSON",
  "go-advanced-language-features/type-assertions":
    "Go Type Assertions: Comma-OK and Common Pitfalls",
  "go-advanced-language-features/type-switch":
    "Go Type Switch: Switching on Dynamic Types",
  "go-advanced-language-features/embedding": "Go Embedding: Struct and Interface Embedding",
  "go-advanced-language-features/error-handling":
    "Go Error Handling: errors.Is, errors.As and Wrapping",
  "go-advanced-language-features/custom-error":
    "Go Custom Errors: Creating and Returning Errors",
  "go-advanced-language-features/panic-and-recover":
    "Go panic and recover: Handling Runtime Failures",
  "go-advanced-language-features/defer":
    "Go defer: Deferred Calls, Evaluation Order and Use Cases",
  "go-advanced-language-features/generics":
    "Go Generics: Type Parameters and Constraints",
  "go-advanced-language-features/generic-functions":
    "Go Generic Functions: Type Parameters and Constraints",
  "go-advanced-language-features/generic-types":
    "Go Generic Types: Stacks, Lists and Constraints",
  "go-advanced-language-features/reflection":
    "Go Reflection: reflect.TypeOf, ValueOf and Struct Tags",
  "go-advanced-language-features/the-unsafe-package":
    "Go unsafe Package: Sizeof, Offsetof and unsafe.Pointer",
};

const GENERIC_DESCRIPTION = /^Learn about .+ in Go\.$/;

/** Strip inline markdown so derived text reads cleanly in search results. */
function stripInlineMarkdown(text: string): string {
  return text
    .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1")
    .replace(/`([^`]*)`/g, "$1")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/\s+/g, " ")
    .trim();
}

function truncate(text: string, limit: number): string {
  if (text.length <= limit) return text;
  const clipped = text.slice(0, limit);
  const lastSpace = clipped.lastIndexOf(" ");
  const cut = lastSpace > limit * 0.6 ? clipped.slice(0, lastSpace) : clipped;
  return `${cut.trimEnd()}…`;
}

/**
 * The page's opening prose, skipping headings, lists, quotes, code and
 * horizontal rules. Normally stops at the first paragraph boundary; when that
 * paragraph is very short, one more is appended so the snippet isn't thin.
 */
function introExcerpt(body: string, limit: number, min = 60): string {
  const parts: string[] = [];
  const buf: string[] = [];
  let inFence = false;

  const flush = (): void => {
    const text = stripInlineMarkdown(buf.join(" "));
    buf.length = 0;
    if (text) parts.push(text.replace(/[:;]+$/, "").trim());
  };

  const joined = (): string => parts.join(" ");
  const complete = (): boolean => joined().length >= min;
  const result = (): string => (joined() ? truncate(joined(), limit) : "");

  for (const raw of body.split(/\r?\n/)) {
    const line = raw.trim();

    if (line.startsWith("```")) {
      flush();
      if (complete()) break;
      inFence = !inFence;
      continue;
    }
    if (inFence) continue;

    if (!line) {
      flush();
      if (complete()) break;
      continue;
    }

    const isStructural =
      /^#{1,6}\s/.test(line) ||
      /^[<>]/.test(line) ||
      /^([-*+]|\d+\.)\s/.test(line) ||
      /^[-=_*]{3,}$/.test(line) ||
      line.startsWith(">") ||
      line.startsWith("|");

    if (isStructural) {
      flush();
      continue;
    }

    // A bare label line (e.g. "Syntax:") is not prose — treat it as noise.
    if (line.length < 40 && line.endsWith(":")) continue;

    buf.push(line);
  }

  flush();
  return result();
}

/**
 * A title suited to search intent without changing the visible H1 or sidebar
 * label. Pages whose title already names Go are left alone.
 */
export function getSeoTitle(doc: Doc): string {
  const key = doc.slug.join("/");
  const override = TITLE_OVERRIDES[key];
  if (override) return override;

  const base = /\bgolang\b|\bgo\b/i.test(doc.title)
    ? doc.title
    : `${doc.title} in Go`;

  // Titles reused across sections (e.g. "Middleware") need disambiguating.
  if (getDuplicateTitles().has(doc.title)) {
    return `${base} — ${getShortSection(doc.section)}`;
  }
  return base;
}

/**
 * Frontmatter descriptions are used when they are genuinely descriptive.
 * Placeholder/truncated ones fall back to the page's own opening paragraph.
 */
export function getSeoDescription(doc: Doc, limit = 155): string {
  // Placeholder bodies must never surface as meta text.
  if (doc.isPlaceholder) {
    return `${doc.title} in Go — part of the ${getShortSection(
      doc.section,
    )} section of ${SITE_NAME}.`;
  }

  const frontmatter = doc.description.trim();
  const usable =
    frontmatter.length >= 50 &&
    !GENERIC_DESCRIPTION.test(frontmatter) &&
    !frontmatter.endsWith(":");

  if (usable) return frontmatter;

  const derived = introExcerpt(doc.body, limit);
  if (derived) return derived;

  return `Learn about ${doc.title.toLowerCase()} in Go, part of the ${getShortSection(
    doc.section,
  )} section of ${SITE_NAME}.`;
}

export function getSeoKeywords(doc: Doc): string[] {
  const short = getShortSection(doc.section);
  const values = [doc.title, `Go ${doc.title}`, short, "Go", "Golang"];
  return [...new Set(values.filter(Boolean))];
}

/**
 * Curated, contextually useful cross-links for concepts that are commonly
 * learned together. Same-section siblings are appended to round out the list.
 */
const RELATED: Record<string, string[]> = {
  "go-advanced-language-features/interfaces": [
    "go-advanced-language-features/empty-interface",
    "go-advanced-language-features/type-assertions",
    "go-advanced-language-features/type-switch",
    "go-advanced-language-features/embedding",
    "go-advanced-language-features/generics",
  ],
  "go-advanced-language-features/empty-interface": [
    "go-advanced-language-features/type-assertions",
    "go-advanced-language-features/type-switch",
    "go-advanced-language-features/interfaces",
    "go-advanced-language-features/generics",
  ],
  "go-advanced-language-features/error-handling": [
    "go-advanced-language-features/custom-error",
    "go-advanced-language-features/panic-and-recover",
    "go-advanced-language-features/defer",
    "go-advanced-language-features/interfaces",
  ],
  "go-advanced-language-features/custom-error": [
    "go-advanced-language-features/error-handling",
    "go-advanced-language-features/panic-and-recover",
    "go-advanced-language-features/interfaces",
  ],
  "go-advanced-language-features/panic-and-recover": [
    "go-advanced-language-features/defer",
    "go-advanced-language-features/error-handling",
    "go-advanced-language-features/custom-error",
  ],
  "go-advanced-language-features/defer": [
    "go-advanced-language-features/panic-and-recover",
    "go-advanced-language-features/error-handling",
  ],
  "go-advanced-language-features/generics": [
    "go-advanced-language-features/generic-functions",
    "go-advanced-language-features/generic-types",
    "go-advanced-language-features/interfaces",
    "go-advanced-language-features/empty-interface",
  ],
  "go-advanced-language-features/type-assertions": [
    "go-advanced-language-features/type-switch",
    "go-advanced-language-features/empty-interface",
    "go-advanced-language-features/interfaces",
  ],
  "go-core-programming/slices": [
    "go-core-programming/arrays",
    "go-core-programming/maps",
    "go-core-programming/pointers",
  ],
  "go-core-programming/pointers": [
    "go-core-programming/methods",
    "go-core-programming/structs",
    "go-core-programming/slices",
  ],
  "go-concurrency/goroutines": [
    "go-concurrency/channels",
    "go-concurrency/select",
    "go-concurrency/waitgroup",
    "go-concurrency/mutex",
    "go-concurrency/race-conditions",
    "go-concurrency/context",
    "go-concurrency/concurrency-patterns",
  ],
  "go-concurrency/channels": [
    "go-concurrency/goroutines",
    "go-concurrency/buffered-channels",
    "go-concurrency/unbuffered-channels",
    "go-concurrency/channel-direction",
    "go-concurrency/select",
    "go-concurrency/deadlocks",
  ],
  "go-concurrency/select": [
    "go-concurrency/channels",
    "go-concurrency/goroutines",
    "go-concurrency/context",
    "go-concurrency/deadlocks",
  ],
  "go-concurrency/mutex": [
    "go-concurrency/rwmutex",
    "go-concurrency/atomic-operations",
    "go-concurrency/race-conditions",
    "go-concurrency/waitgroup",
  ],
  "go-concurrency/context": [
    "go-concurrency/goroutines",
    "go-concurrency/channels",
    "go-concurrency/select",
    "go-concurrency/race-conditions",
  ],
  "go-rest-api-development/rest-api-fundamentals": [
    "go-rest-api-development/api-routing",
    "go-rest-api-development/crud-apis",
    "go-rest-api-development/http-status-codes",
    "go-rest-api-development/error-responses",
    "go-rest-api-development/authentication",
  ],
  "go-http-and-networking/http-fundamentals": [
    "go-http-and-networking/net-http",
    "go-http-and-networking/http-server",
    "go-http-and-networking/http-client",
    "go-http-and-networking/request-and-response",
  ],
  "go-database-programming/database-fundamentals": [
    "go-database-programming/database-sql",
    "go-database-programming/connecting-postgresql",
    "go-database-programming/crud-with-postgresql",
    "go-database-programming/transactions",
    "go-database-programming/pgx",
  ],
};

const RELATED_LIMIT = 8;

/** Curated cross-links first, then same-section siblings. */
export const getRelatedDocs = cache((key: string): Doc[] => {
  const docs = getDocs();
  const sectionSlug = key.split("/")[0];
  const seen = new Set<string>([key]);
  const related: Doc[] = [];

  const add = (candidate: string): boolean => {
    if (seen.has(candidate) || related.length >= RELATED_LIMIT) return false;
    const doc = docs.find((d) => d.slug.join("/") === candidate);
    if (!doc) return false;
    seen.add(candidate);
    related.push(doc);
    return true;
  };

  for (const candidate of RELATED[key] ?? []) add(candidate);

  for (const doc of docs) {
    if (related.length >= RELATED_LIMIT) break;
    if (doc.slug[0] !== sectionSlug) continue;
    add(doc.slug.join("/"));
  }

  return related;
});

export type Crumb = { name: string; href: string };

export function getDocBreadcrumbs(doc: Doc): Crumb[] {
  const href = `/docs/${doc.slug.join("/")}`;
  return [
    { name: "Docs", href: "/docs" },
    { name: getShortSection(doc.section), href: `/docs/${doc.slug[0]}` },
    { name: doc.title, href },
  ];
}

export function getSectionBreadcrumbs(sectionSlug: string, sectionTitle: string): Crumb[] {
  return [
    { name: "Docs", href: "/docs" },
    { name: getShortSection(sectionTitle), href: `/docs/${sectionSlug}` },
  ];
}

export function breadcrumbJsonLd(crumbs: Crumb[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: crumbs.map((crumb, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: crumb.name,
      item: absoluteUrl(crumb.href),
    })),
  };
}
